#paths-ignore:
#  - "**/*.min.js"
#  - "src/test/**"
#  - "**/*.js.map"
#  - "**/js/ext/**"
#  - "**/js/libs/**"
#  - "**/plugins/**"
#  - "**/main/resources/**"
#  - "**/js/ace/**"
#  - "**/js/backbone/**"
#  - "**/js/jquery*/**"
#  - "**/js/angular/**"
#  - "resources/**"
#  - "docs/vendor/**"
#  - "config/checkstyle/checkstyle.xml"
