paths-ignore:
  - "src/test/**"
  - "**/*.min.js"
  - "**/js/angular/angular.js"
  - "**/*.js.map"
  - "**/src/main/resources/js/ext/**"
  - "**/plugins/**"
  - "src/main/resources/**"
  - "src/main/resources/webgoat/static/**"
  - "**/src/main/resources/**"
  - "**/js/ace/**"
  - "resources/**"
  - "docs/vendor/**"
  - "config/checkstyle/checkstyle.xml"
