paths-ignore:
  - "src/test/**"
  - "**/*.min.js"
  - "**/js/angular/angular.js"
  - "**/*.js.map"
  - "**/src/main/resources/js/ext/**"
  - "**/plugins/**"
  - "src/main/resources/static/**"
  - "webgoat-container/src/main/resources/static/**"
